### ***Fancy Indexing***

In [17]:
import numpy as np
import time as tl

In [12]:
# arr = np.array([1,2,4,5,6,3,2,8,9])
# print(arr)

# Fancy Indexing -
# newArr = arr[[8,3,4,6,7]]
# print(newArr)

# newArr[2] = 45
# print(arr)
# print(newArr)


# positive indexing - 0 to len-1
# negative indexing - -1 to -len

# negative fancy indexing -
# arr = np.array([1,2,4,5,6,3,2,8,9])
# print(arr)
# negNewArr = arr[[-2, -5, -8, -3, -1]]
# print(negNewArr)

# Normal Indexing -
# print(arr[0])
# print(arr[1])
# print(arr[2])
# print(arr[3])
# print(arr[4])


[1 2 4 5 6 3 2 8 9]
[8 6 2 2 9]


# ***Boolean Masking***

In [21]:
# # whenever we need to filter the NumPy

# arr = np.array([1,2,4,5,6,3,2,8,9])
# print(arr)

# start_time = tl.time()
# evenArr = arr[arr%2 != 0]
# # print(evenArr)
# end_time = tl.time()
# print(f"time taken to filter an numpy array - {end_time - start_time}")

# li = [1,2,4,5,6,3,2,8,9]
# start_time = tl.time()
# evenLi = []
# for i in li:
#   if i%2 == 0:
#     evenLi.append(i)

# evenArr = np.array(evenLi)
# end_time = tl.time()

# print(f"time taken to filter an python list and then converting it into numpy array - {end_time - start_time}")

[1 2 4 5 6 3 2 8 9]
time taken to filter an numpy array - 0.00013327598571777344
time taken to filter an python list and then converting it into numpy array - 0.00015354156494140625


# ***Type-Casting of NumPy Arrays***

In [42]:
# creating NumPy Arrays -
# - np.array()
# - np.arange()
# - np.linspace()
# - np.zeros
# - np.ones
# - np.full

# zeroArr = np.zeros([2])     # 1D Zeroth Array
# zeroArr = np.zeros([4,3])       # 2D Zeroth Array
# zeroArr = np.zeros([2, 3, 4])       # 3D Zeroth Array
# zeroArr

# onesArr = np.ones([2])     # 1D ones Array
# onesArr = np.ones([4,3])       # 2D ones Array
# onesArr = np.ones([2, 3, 4])       # 3D Zeroth Array
# onesArr

# # fullArr = np.full([2])     # 1D full Array
# fullArr = np.full([4,3], 9)       # 2D full Array
# fullArr = np.full([2, 3, 4], 7)       # 3D full Array
# fullArr



# if I want to type cast any numpy array then -
# 1. the first way to type cast our numpy array is by changing the dtype=np.dataType - it will type cast the original numpy array!
# fullArr = np.full([4,4], 22, dtype=np.float64)
# fullArr


# 2. second way to type cast an numpy array and by this we'll generate the shallow copy of the original array!
# fullArr = np.full([4,4], 9, dtype=np.float64)
# print(f"before type casting - \n{fullArr}")

# typeCastedArr = fullArr.astype(np.int64)
# print(f"before type casting - \n{typeCastedArr}")

# typeCastedArr[0] = [1,2,3,4]
# print(f"After type casting - \n{fullArr}")
# print(f"After type casting - \n{typeCastedArr}")

before type casting - 
[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]
before type casting - 
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
After type casting - 
[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]
After type casting - 
[[1 2 3 4]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
