### ***pre-buil methods to manipulate NumPy Array***

In [2]:
import numpy as np

In [62]:
# np.zeros
# np.ones
# np.full
# np.eye
# np.indentity

# arr = np.arange(1,13).reshape(3,4)
# print(arr)

# iMatrix = np.eye(4,3)      # Indentity Matrix
# print(iMatrix)

# iMatrix = np.identity(2)      # Identity Matrix
# print(iMatrix)



# random methods - it will help us to generate a random array
# randomArr = np.random.rand(7)     # (0 to 1)*100
# randomArr = np.random.rand(7)*10   # 0 to 10
# randomArr = np.random.rand(7)*100   # 0 to 100
# print(randomArr)
# randomArr = np.random.rand(2,3)*100   # 0 to 100
# print(randomArr)
# randomArr = np.random.rand(2,3,4)*100   # 0 to 100
# print(randomArr)

# randIntArr = randomArr.astype(np.int64)
# print(randIntArr)


# np.randn()
# arr = np.random.randn(5)
# print(arr)
# rest demostration, student's will try and code


# np.randint()
# intArr = np.random.randint(1, 15, size=[2,3,4])
# print(intArr)



[[[ 8 12  9  7]
  [ 9 12 11  4]
  [ 9  8  6 14]]

 [[ 8 10  1 14]
  [ 6  3  1  4]
  [ 2  3  5  7]]]


In [80]:
# Agregation Methods - it will help us to provide a statistical summary of an Array

# arr = np.array([1,5,7,8,9,6,3,2])
# print(arr)
# sumOfArr = np.sum(arr)
# print(sumOfArr)


# li = [1,2,3,4]
# ekorli = [5,6,7,8]
# print(li + ekorli)


arrli = np.array([1,2,3,4])
arrekorli = np.array([5,6,7,8])
# # print(arrli + arrekorli)
# # newArr = np.sum(arrli + arrekorli)
# newArr = np.sum([arrli, arrekorli])
# print(newArr)

# concatedArr = np.concatenate([arrli, arrekorli])
# concatedArr = np.concatenate((arrli, arrekorli))
# print(concatedArr)


# minValue = np.min(arrli)
# print(minValue)

# minValue = np.max(arrekorli)
# print(minValue)

# meanValue = np.mean(arrli)
# print(meanValue)
# meanValue = np.average(arrli)
# print(meanValue)
# meanValue = np.median(arrli)
# print(meanValue)

12.0
