### ***Slicing in NumPy (1D, 2D & 3D)***

In [1]:
import numpy as np

In [55]:
# .shape
# .size
# .ndim

# arr = np.arange(35)
# arr = np.arange(1, 36)
# arr = np.arange(1, 36, 2)
# arr.size


# arr = np.arange(1, 36)
# print(arr)

# Slicing with 1D array - array[start:end:skip]
# newArr = arr[0:5]
# print(newArr)

# newArr = arr[16:21]
# newArr

# newArr = arr[:10]
# newArr

# newArr = arr[:]
# newArr

# newArr = arr[::1]
# newArr

# newArr = arr[::7]
# newArr

# newArr = arr[::-1]
# newArr

# newArr = arr[::-2]
# newArr

# newArr = arr[::-1]
# newArr



# Slicing in 2D-Array - Rows and columns - arr[start:end:skip, start:end:skip]

# arr = np.arange(1, 36).reshape(7,5)
# print(arr)

# newArr = arr[:, 4]
# print(newArr)

# newArr = arr[:, 2:5:2]
# print(newArr)



# Slicing in 3D-Array - Pages, Rows and columns - arr[start:end:skip, start:end:skip, start:end:skip]
# arr = np.arange(1, 43).reshape(2,3,7)
# print(arr)

arr= np.arange(1,(2 * 3 * 7) + 1).reshape(2,3,7)
print(arr)
# print(arr[1, :, 3:4])
print(arr[1, 1:, 5:])

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]
  [15 16 17 18 19 20 21]]

 [[22 23 24 25 26 27 28]
  [29 30 31 32 33 34 35]
  [36 37 38 39 40 41 42]]]
[[34 35]
 [41 42]]
