### ***Re-Shaping of an Array in NumPy***

In [3]:
import numpy as np
import time as tl

In [1]:
# reshaping in numpy?
# - when we re-shape an numpy array. that means if we manipulate the dimensions of the numpy array then we are clearly re-shaping it

In [14]:
# arr = np.arange(1, 11)
# print(f"Original array - \n{arr}")

# # reshapedArr = arr.reshape(2,3)      # cannot reshape array of size 10 into shape (2,3) coz the matrix count doesn't matches
# # reshapedArr = arr.reshape(2,5)
# reshapedArr = arr.reshape(5,2)
# print(f"Re-Shaped array - \n{reshapedArr}")
# arr = np.arange(1, 11)

# Re-shaping of 3D Array -
# arr = np.arange(1, 13)
# reshapedArr = arr.reshape(1,4,3)
# reshapedArr = arr.reshape(1,3,4)
# reshapedArr = arr.reshape(4, 1,3)
# print(f"Original array - \n{arr}")
# print(f"Re-Shaped array - \n{reshapedArr}")

In [35]:
arr = np.arange(1,36)
# print(arr)

# converting 1-D Array into 2-D Array
newArr = arr.reshape(5,7)
print(f"original 2-D Array - {newArr}")


# converting 2-D Array into 1-D Array using flatten methods-
# flattenArr = newArr.flatten()
# print(flattenArr)

# converting 2-D Array into 1-D Array using ravel methods-
# flatArr = newArr.ravel()
# print(flatArr)


# difference between flatten and ravel
# flattenArr = newArr.flatten()
# print(f"flat array without update (flatten) - {flattenArr}")

# flatArr = newArr.ravel()
# print(f"flat array without update (ravel) - {flatArr}")

# flattenArr[0] = 77
# print(f"flat array with updates (flatten) - {flattenArr}")
# print(f"original 2-D Array - {newArr}")

# flatArr[0] = 77
# print(f"flat array with updates (ravel) - {flatArr}")
# print(f"original 2-D Array - {newArr}")

original 2-D Array - [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]
flat array without update (ravel) - [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]
flat array with updates (ravel) - [77  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]
original 2-D Array - [[77  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]
